
export const cars = [
  "/static/images/cars/car_black_small_1.png",
  "/static/images/cars/car_blue_small_1.png",
  "/static/images/cars/car_green_small_1.png",
  "/static/images/cars/car_red_small_1.png",
  "/static/images/cars/car_yellow_small_1.png",

  "/static/images/cars/car_black_small_2.png",
  "/static/images/cars/car_blue_small_2.png",
  "/static/images/cars/car_green_small_2.png",
  "/static/images/cars/car_red_small_2.png",
  "/static/images/cars/car_yellow_small_2.png",

  "/static/images/cars/car_black_small_3.png",
  "/static/images/cars/car_blue_small_3.png",
  "/static/images/cars/car_green_small_3.png",
  "/static/images/cars/car_red_small_3.png",
  "/static/images/cars/car_yellow_small_3.png",

  "/static/images/cars/car_black_small_4.png",
  "/static/images/cars/car_blue_small_4.png",
  "/static/images/cars/car_green_small_4.png",
  "/static/images/cars/car_red_small_4.png",
  "/static/images/cars/car_yellow_small_4.png",

  "/static/images/cars/car_black_small_5.png",
  "/static/images/cars/car_blue_small_5.png",
  "/static/images/cars/car_green_small_5.png",
  "/static/images/cars/car_red_small_5.png",
  "/static/images/cars/car_yellow_small_5.png",
]

export const tiles = [
  "/static/images/tiles/0.png",
  "/static/images/tiles/1.png",
  "/static/images/tiles/2.png",
  "/static/images/tiles/3.png",
  "/static/images/tiles/4.png",
  "/static/images/tiles/5.png",
  "/static/images/tiles/6.png",
  "/static/images/tiles/7.png",
  "/static/images/tiles/8.png",
  "/static/images/tiles/9.png",
  "/static/images/tiles/10.png",
  "/static/images/tiles/11.png",
  "/static/images/tiles/12.png",
  "/static/images/tiles/13.png",
  "/static/images/tiles/14.png",
  "/static/images/tiles/15.png",
  "/static/images/tiles/16.png",
  "/static/images/tiles/17.png",
  "/static/images/tiles/18.png",
  "/static/images/tiles/19.png",
  "/static/images/tiles/20.png",
  "/static/images/tiles/21.png",
  "/static/images/tiles/22.png",
  "/static/images/tiles/23.png",
  "/static/images/tiles/24.png",
  "/static/images/tiles/25.png",
  "/static/images/tiles/26.png",
  "/static/images/tiles/27.png",
  "/static/images/tiles/28.png",
  "/static/images/tiles/29.png",
  "/static/images/tiles/30.png",
  "/static/images/tiles/31.png",
  "/static/images/tiles/32.png",
  "/static/images/tiles/33.png",
  "/static/images/tiles/34.png",
  "/static/images/tiles/35.png",
  "/static/images/tiles/36.png",
  "/static/images/tiles/37.png",
  "/static/images/tiles/38.png",
  "/static/images/tiles/39.png",
  "/static/images/tiles/40.png",
  "/static/images/tiles/41.png",
  "/static/images/tiles/42.png",
  "/static/images/tiles/43.png",
  "/static/images/tiles/44.png",
  "/static/images/tiles/45.png",
  "/static/images/tiles/46.png",
  "/static/images/tiles/47.png",
  "/static/images/tiles/48.png",
  "/static/images/tiles/49.png",
  "/static/images/tiles/50.png",
]
